package com.eznebula.domain.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Client Node Entity
 * Represents a client device connected to a network group
 */
@Entity
@Table(name = "client_nodes", indexes = {
    @Index(name = "idx_group_ip", columnList = "groupId,virtualIp", unique = true),
    @Index(name = "idx_client_name", columnList = "clientName")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClientNode {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Reference to the network group
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id", nullable = false)
    private NetworkGroup networkGroup;

    /**
     * Client-provided device name
     */
    @Column(nullable = false, length = 128)
    private String clientName;

    /**
     * Allocated virtual IP address (e.g., "10.168.1.5")
     */
    @Column(nullable = false, length = 32)
    private String virtualIp;

    /**
     * Allocated CIDR suffix (e.g., "24" for /24 netmask)
     */
    @Column(nullable = false)
    private Integer cidrSuffix;

    /**
     * Client's public key (Ed25519)
     */
    @Column(nullable = false, length = 512)
    private String publicKey;

    /**
     * Signed certificate content (generated by CA)
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String certificate;

    /**
     * Certificate expiration time
     */
    @Column(nullable = false)
    private LocalDateTime certificateExpiresAt;

    /**
     * Last seen timestamp (for health monitoring)
     */
    @Column
    private LocalDateTime lastSeenAt;

    /**
     * Whether this node is active
     */
    @Column(nullable = false)
    @Builder.Default
    private Boolean active = true;

    @CreationTimestamp
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
